export const REQUEST_GET_NEWS_LIST_SUCCESS = 'REQUEST_GET_NEWS_LIST_SUCCESS';

export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const CHANGE_SHOW_MODAL='CHANGE_SHOW_MODAL';
export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';